package cn.izengmei.demo;

import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;

public class Write {
    public static void method2(String file, String conent) {
        BufferedWriter out = null;
        try {
            out = new BufferedWriter(new OutputStreamWriter(
                    new FileOutputStream(file, true)));
            out.write(conent+"\r\n");
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                out.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public static void main(String[] args) {
        method2("1.txt","CCO21038.1,MRQKLILCLMALFAVVSVEAKVTLPRLVSDGMVLQRDEPLKIWGWASAGETVKVTFLDGSYKTKADRKGNWCVELPAHKAGGPYTMRVNGIEIRDILIGDVWLCSGQSNMELTMDRVLDLYADEVADANYPFIRYFRVPMKYNFRNEEADLQGGRWETATPGNLPDLSAVAWFFAKELYDTYGVPIGLINTSIGGSPAEAWIGAGALKDYPHYLEAARESAAQGYIESVTKADQRAGEEWRRTMDEKDPGVGVWNREDFDDSDWASISLPGYWADKGAGQVNGSVWFRKEIGLPASLAGKAATLRMGTIVDADSTFVNGTFVGTVSYQYPPRIYTIPAGVLKEGRNNITVRVTSNAGRGGFVEEKPYELIVEGDGIDLTGDWKYRVGAGMPPAAPQTFFQYKPTGLYNGMIAPLKNYALKGFLWYQGESNAGKPNEYKGLMAALINDWRAKWNKPRMPFIYAQLPGFMKENKLPVESGWAELREAQRQTLEIPHTGMAVTIDAGEWNDIHPLNKKTVGERLALEARRVAYGESGIVSTGPMYESAIVEDGGIVLAFSSVGSGIYTNLDLAGFTIAGPDGRYVWANAAVVSGGKIRVWSDWVPEPVSVRYAWADNPVGANLRNKEGLPASPFRADVETGVITGNGTGTHGGYDWELWRDRGDVCMILKEGGAFECSWDNINNALFRTGKKFDATRTHDQLGDISLDYGCDYHPDGNSYLCVYGWSVDPLIEFYVVEAWGNWRPPGAESKGTVEIDGGTYDIYRTTRVEQPSIQGTTTFEQYWSVRTDKKTSGTVSVSEHIRAWEKMGMELGKIYEVAFCVEGYQSRGTADVYKMSFGEQANK");
        method2("1.txt","ADB28453.1,MVAFTSLLAGFTAITGVLSAPTEVEVVDVEKRQTIGPGTGTNNGYYYSYWNDGHAGVTYTNGASGSFSVNWVNSGNFVGGKGWNPGSSTRTINYSGSYNPNGNSYLSVYGWSKNPLIEYYIVENFGTYNPSTGTTKLGEVTSDGSVYDIYRTQRVNQPSIIGTATFYQYWSVRRNHRSSGSVNVGNHFNAWRNLGLTLGQLDYQILAVEGYFSSGNANINVS");
    }
}
